# Generated by Django 4.0.2 on 2022-03-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_views_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='post_topic',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.topics'),
        ),
    ]
