# Generated by Django 4.0.2 on 2022-03-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_topics_post_topic_posts_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
